"""Add CalendarSave model

Revision ID: 285f9d3b36c6
Revises: e73a4af54e55
Create Date: 2025-12-20 03:01:12.478139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285f9d3b36c6'
down_revision = 'e73a4af54e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_save',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_save')
    # ### end Alembic commands ###
