"""Add GuestToken model

Revision ID: 31a68faeb89c
Revises: 285f9d3b36c6
Create Date: 2025-12-23 18:14:44.883636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a68faeb89c'
down_revision = '285f9d3b36c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('contact_permission', sa.Boolean(), nullable=True),
    sa.Column('linked_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linked_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_token_ip_address'), ['ip_address'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('guest_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_token_ip_address'))

    op.drop_table('guest_token')
    # ### end Alembic commands ###
