"""Add government registration support and subscription metrics

Revision ID: 3382b385b4ef
Revises: d48fb94638d3
Create Date: 2026-01-12 21:52:31.982877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3382b385b4ef'
down_revision = 'd48fb94638d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('government_domain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_government_domain_domain'), ['domain'], unique=True)

    op.create_table('subscription_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_name')
    )
    op.create_table('government_registration_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_token')
    )
    with op.batch_alter_table('verified_break', schema=None) as batch_op:
        batch_op.drop_index('ix_verified_break_district_name')
        batch_op.drop_index('ix_verified_break_normalized_district_name')
        batch_op.drop_index('ix_verified_break_school_year')
        batch_op.drop_index('ix_verified_district_year')

    op.drop_table('verified_break')
    with op.batch_alter_table('school_calendar', schema=None) as batch_op:
        batch_op.drop_index('ix_calendar_school_year')

    op.drop_table('school_calendar')
    with op.batch_alter_table('school_entity', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_government', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('government_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('government_oath_accepted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('verified_holiday', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verified_holiday', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('government_oath_accepted')
        batch_op.drop_column('government_verified')
        batch_op.drop_column('is_government')

    with op.batch_alter_table('school_entity', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    op.create_table('school_calendar',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('school_year', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('source_filename', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('analysis_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('analysis_version', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('analysis_generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ingest_metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['school_entity_id'], ['school_entity.id'], name='school_calendar_school_entity_id_fkey'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.id'], name='school_calendar_uploaded_by_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='school_calendar_pkey'),
    sa.UniqueConstraint('file_hash', name='school_calendar_file_hash_key'),
    sa.UniqueConstraint('school_entity_id', 'school_year', name='uix_entity_school_year')
    )
    with op.batch_alter_table('school_calendar', schema=None) as batch_op:
        batch_op.create_index('ix_calendar_school_year', ['school_year'], unique=False)

    op.create_table('verified_break',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('district_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('normalized_district_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('school_year', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('break_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('verified_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='verified_break_pkey'),
    sa.UniqueConstraint('normalized_district_name', 'school_year', 'break_type', name='uix_district_year_break')
    )
    with op.batch_alter_table('verified_break', schema=None) as batch_op:
        batch_op.create_index('ix_verified_district_year', ['normalized_district_name', 'school_year'], unique=False)
        batch_op.create_index('ix_verified_break_school_year', ['school_year'], unique=False)
        batch_op.create_index('ix_verified_break_normalized_district_name', ['normalized_district_name'], unique=False)
        batch_op.create_index('ix_verified_break_district_name', ['district_name'], unique=False)

    op.drop_table('government_registration_request')
    op.drop_table('subscription_metrics')
    with op.batch_alter_table('government_domain', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_government_domain_domain'))

    op.drop_table('government_domain')
    # ### end Alembic commands ###
