"""Add stripe_customer_id and stripe_subscription_id to User

Revision ID: 5df76d935bfb
Revises: b0ab18e16d43
Create Date: 2026-01-15 19:11:54.139714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df76d935bfb'
down_revision = 'b0ab18e16d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_vote', schema=None) as batch_op:
        batch_op.drop_constraint('feedback_vote_post_id_user_id_key', type_='unique')
        batch_op.create_unique_constraint('unique_user_post_vote', ['post_id', 'user_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_user_stripe_customer_id'))
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    with op.batch_alter_table('feedback_vote', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_post_vote', type_='unique')
        batch_op.create_unique_constraint('feedback_vote_post_id_user_id_key', ['post_id', 'user_id'])

    # ### end Alembic commands ###
