"""Add referral program fields to User model

Revision ID: b0ab18e16d43
Revises: 3382b385b4ef
Create Date: 2026-01-12 22:19:23.006918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ab18e16d43'
down_revision = '3382b385b4ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('referred_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referral_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referral_tokens_earned', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_referral_code'), ['referral_code'], unique=True)
        batch_op.create_foreign_key(None, 'user', ['referred_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_referral_code'))
        batch_op.drop_column('referral_tokens_earned')
        batch_op.drop_column('referral_count')
        batch_op.drop_column('referred_by_id')
        batch_op.drop_column('referral_code')

    # ### end Alembic commands ###
