"""Add is_verified source confidence to VerifiedHoliday

Revision ID: d48fb94638d3
Revises: e55a79463228
Create Date: 2026-01-11 23:03:48.130398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48fb94638d3'
down_revision = 'e55a79463228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_file', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('school_entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_entity_slug'), ['slug'], unique=True)

    with op.batch_alter_table('verified_holiday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verified_holiday', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('confidence')
        batch_op.drop_column('source')
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('school_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_entity_slug'))

    with op.batch_alter_table('calendar_file', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
