"""Add SchoolEntity and SchoolCalendar models

Revision ID: e55a79463228
Revises: 31a68faeb89c
Create Date: 2025-12-26 19:25:55.215844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55a79463228'
down_revision = '31a68faeb89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('district_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('nces_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'normalized_name', 'county', name='uix_entity_type_name_county')
    )
    with op.batch_alter_table('school_entity', schema=None) as batch_op:
        batch_op.create_index('ix_entity_county_name', ['county', 'normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_entity_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_entity_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('school_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_entity_id', sa.Integer(), nullable=False),
    sa.Column('school_year', sa.String(length=20), nullable=False),
    sa.Column('source_filename', sa.String(length=500), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=True),
    sa.Column('analysis_version', sa.String(length=20), nullable=True),
    sa.Column('analysis_generated_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ingest_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_entity_id'], ['school_entity.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash'),
    sa.UniqueConstraint('school_entity_id', 'school_year', name='uix_entity_school_year')
    )
    with op.batch_alter_table('school_calendar', schema=None) as batch_op:
        batch_op.create_index('ix_calendar_school_year', ['school_year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_calendar', schema=None) as batch_op:
        batch_op.drop_index('ix_calendar_school_year')

    op.drop_table('school_calendar')
    with op.batch_alter_table('school_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_entity_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_school_entity_county'))
        batch_op.drop_index('ix_entity_county_name')

    op.drop_table('school_entity')
    # ### end Alembic commands ###
